### ISSUE TITLE
getAgriMet.data error

### ISSUE THREAD

**Issue by kendrakaiser** [rhlee12/RNRCS#11]
When I run
```R
fafi=getAgriMet.data(site_id="FAFI", timescale="hourly", DayBgn = "1987-06-25", DayEnd="2020-07-01", pCodes=c("OB", "PC","SI", "SQ")) 

Error in if (dataEndIndex > dataStartIndex) { : 
  argument is of length zero
```
Looking at the data online, "SQ" only went back to 1988, so I assumed it was the one variable that was throwing it off - is there a way to return a partial record (e.g. when new sensors get added?)

Re running the code without "SQ"  I got the same error even though the URL does work https://www.usbr.gov/pn-bin/instant.pl?station=FAFI&year=1987&month=6&day=25&year=2020&month=7&day=1&pcode=OB&pcode=PC&pcode=SI&pcode=SQ&print_hourly=1

I also tried incrementally making the start date later, and for some reason it works if the start date is after 1992....

**Comment by rhlee12** [comment]
Hi @kendrakaiser, 

When I run the function line-by-line for FAFI and the other parameters you specify, I do get data returned. The check that data are of length > 0 (which is what errored out with `Error in if (dataEndIndex > dataStartIndex) { :  argument is of length zero`) worked too. But when I simply  run the code you included, I do get the error.

That data returned is ~ 50mb, and 286k lines long, and I think what is happening is the server gives up part way thru serving the data. For example, one attempted query resulted in only 12 years of data, with an incomplete line of data being served (note the `7.` on the final line below):
```
>fafi=getAgriMet.data(site_id="FAFI", timescale="hourly", DayBgn = "1987-06-25", DayEnd="2020-07-01", pCodes=c("OB", "PC","SI", "SQ"))
# function printing tail of raw return
[1] "04/22/2008 17:00,      44.77 ,       7.15 ,      60.06 ,     981.39 "
[2] "04/22/2008 18:00,      43.95 ,       7.15 ,      42.48 ,    1023.87 "
[3] "04/22/2008 19:00,      43.10 ,       7.15 ,      25.68 ,    1049.55 "
[4] "04/22/2008 20:00,      39.87 ,       7.15 ,       8.11 ,    1057.66 "
[5] "04/22/2008 21:00,      37.18 ,       7.15 ,       0.58 ,    1058.24 "
[6] "04/22/2008 22:00,      39.27 ,       7."                             
```
This also explains why there was an error for `dataEndIndex > dataStartIndex`; the marker for the end of the data isn't returned, so that logical can't be evaluated.

I suspect the server can't reliably handle returning that much data at once, but I've added some changes to the code to return what ever data it can return, while printing a warning that the full dataset was not returned. I'll push those changes up here shortly, and you can try the git install command again to get the latest.


I'd recommend segementing your data pulls into smaller time periods, then combining the outputs into a single data frame, using something like the code below:
```
startDate="1987-06-25"
endDate="2020-07-01"

fiveYearDates=c(as.character(seq.Date(from=as.Date(startDate), to=as.Date(endDate), by="5 years")), endDate)

fafiDF=data.frame()

for(i in 2:length(fiveYearDates)){
   tempDF= getAgriMet.data(site_id="FAFI", timescale="hourly", DayBgn = fiveYearDates[i-1], DayEnd=fiveYearDates[i], pCodes=c("OB", "PC","SI", "SQ"))
   fafiDF=plyr::rbind.fill(fafiDF, tempDF)
}
```


Finally, I suspect that the partial availability of the SQ code may be an issue, I'll keep working on a way to handle that in the function. The code above should handle that issue in the meantime.
